### ISSUE TITLE
Stuck in Creating Container Mode.

### ISSUE THREAD

**Issue by jkuruzovich** [GoogleCloudPlatform/gke-jupyter-classroom#1] opened 2017-01-20 00:27 UTC
I've gone through this tutorial multiple times and each time run into an issue, though on the surface the create script seems to be working.  

After further investigating I've found that the jupyterhub gets stuck in a  ContainerCreating status.  I've double checked multiple times that the file server is available. I've tried deleting the container but when it re-spawns it continues to hang. 

NAMESPACE     NAME                                                                   READY     STATUS              RESTARTS   
jupyterhub    jupyterhub-750308639-47o29        0/1       ContainerCreating   0          11m

I believe I have correctly setup the file server but my guess is that there is a step missing to allow the file server to mount appropriately. Any ideas of where I could dig further?

**Comment by sveesible** [comment] 2017-01-20 03:34
Sorry for the frustration, it could be some recent updates to Kubernetes have changed and thus could be in the yaml.  kubectl get events  might give more info.  I will try to reproduce asap

**Comment by sveesible** [comment] 2017-01-24 20:04
There seems to be two issues that could be affecting you.
If you chose the "SSD" option when creating the Single-Node File Server, there is a bug in the mount process, and thus the secondary data disk will not get formatted, mounted and loaded into the export.conf.  

Secondly, name recognition from the GKE Host nodes is not resolving hostnames of other GCE VM's, so make sure to use the IP address of your filer VM in your initialization script.

**Comment by sveesible** [comment] 2017-01-24 20:12
If you want to use the current Filer Node you created, you can try to use this script to fix it manually
`export DVC="/dev/disk/by-id/$(ls /dev/disk/by-id | grep "google-$(hostname)")"

export MNTPT="/"$(ls /dev/disk/by-id | grep "google-$(hostname)" | awk -F"-" '{print $NF}')

mkfs.ext4 $DVC

mkdir -p $MNTPT

mount -t ext4 $DVC $MNTPT

echo "$MNTPT *(rw,no_root_squash,subtree_check)" >> /etc/exports

/etc/init.d/nfs-kernel-server restart
`

**Comment by jkuruzovich** [comment] 2017-01-25 15:47
Thanks so much for help.  I just tried wiping out everything and repeating. I did not include the SSD version when creating the file system.  I think that makes sense that somehow it is getting stuck with trying to connect to the file server the fileserver. Here is the config:
![Imgur](http://i.imgur.com/Dqil9nr.png)

I'm curious if you were able to reproduce using the version of Kubernetes that is active on the Google Cloud platform? I'm still running into the same issue.  

I'm using the internal filer IP of the file server as follows: 
./gke-jupyter-classroom.sh -v --cluster-name jupytercluster1 --admin-user jkuruzovich@gmail.com --filer-ip 10.142.0.3 --filer-path /jupyterhub --zone us-east1-d --autoscale-nodes 6 deploy

Everything seems to be launching fine.  
jupyterhub    jupyterhub-750308639-b23t5                                             0/1       ContainerCreating   
(Lots of other pods are running)

jupyterhub-filer-vm                             us-east1-d  n1-standard-1               10.142.0.3

**Comment by sveesible** [comment] 2017-02-02 05:04
What seems to be happening is that the Nginx proxy service isn't properly getting it's configuration loaded, so I logged into the nginx container and did and service nginx force-reload and then everything worked properly. 

I'm not sure yet why, or what changed, but likely it's a sequencing thing, as the config file is auto generated at startup, and relies on the environment variables assigned by K8's to the docker instance that define the service IP's and ports.

**Comment by ssable** [comment] 2017-02-24 09:48
I also tried to run this tutorial and it failed, probably in the same way as it did with @jkuruzovich.

The issue comes from Single Node File Server which is broken at the moment. I tried without SSD and using other filesystems than zfs, but in all cases the deployment fails in different ways.

So I wanted to create a nfs server directly in the container rather than using the single node file server.
I found this example in kubernetes repo:
https://github.com/kubernetes/kubernetes/tree/master/examples/volumes/nfs

Unfortunately this example is also broken. So I applied the proposed correction from:
https://github.com/kubernetes/kubernetes/issues/24687

That got me a working nfs server directly in the container rather than using the (broken) Single Node File Server. I created a fork of this project and modified it to use the nfs server in container engine:
https://github.com/ssableslb/gke-jupyter-classroom

**Comment by sveesible** [comment] 2017-02-25 20:06
This is an approach I had originally attempted to use, but the kernel running GKE was not compatible with the NFS server modules running within a container.  This is good news that you got this part working. I will try to test my original NFS container again and then add it to the repository, which will be better than depending on the Launcher version of the NFS filer.

**Comment by jkuruzovich** [comment] 2017-02-25 23:40
The documentation for a helm based instillation from the folks at Berkley has recently been updated and is in active use. https://github.com/data-8/jupyterhub-k8s. Might be worth a try.

**Comment by mrubashkin-svds** [comment] 2017-03-17 20:00
I just tried the tutorial using the .sh script from the Master branch. Using the recommendation from @jkuruzovich, I still encountered these errors:
<img width="1390" alt="screen shot 2017-03-17 at 12 58 07 pm" src="https://cloud.githubusercontent.com/assets/17418749/24060720/b7ffeab2-0b11-11e7-8587-0f74956640cb.png">
I'm going to try @ssableslb 's solution next

**Comment by sveesible** [comment] 2017-03-21 15:54
This is still the filer server not mounting properly. The script above in the comment thread from jan 24th should help fix the filer server's mounting problem

**Comment by mrubashkin-svds** [comment] 2017-03-23 00:25
Thanks for the help @sveesible, using nfs storage (as per @jkuruzovich's above image) I had to do a bit different series of commands

```
export DVC="/dev/disk/by-id/$(ls /dev/disk/by-id | grep "google-$(hostname)")"
export MNTPT="/"$(ls /dev/disk/by-id | grep "google-$(hostname)" | awk -F"-" '{print $NF}')
sudo apt-get upgrade xfsprogs
sudo mkfs -t xfs $DVC
sudo mkdir -p $MNTPT
sudo mount $DVC $MNTPT
sudo su
echo "$MNTPT *(rw,no_root_squash,subtree_check)" >> /etc/exports
/etc/init.d/nfs-kernel-server restart
```

Then running `df -h` I could confirm that /jupyterhub was added:
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       9.8G  2.4G  6.9G  26% /
udev             10M     0   10M   0% /dev
tmpfs           743M  8.4M  735M   2% /run
tmpfs           1.9G     0  1.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           1.9G     0  1.9G   0% /sys/fs/cgroup
tmpfs           372M     0  372M   0% /run/user/1001
/dev/sdb         10G   33M   10G   1% /jupyterhub

Unfortunately though after all of that, I still get a failing Kubernetes setup, I'll get back to you with the details of that failure soon

**Comment by ghost** [comment] 2017-03-24 04:51
@sveesible's script worked for me.  'mkfs.ext4' is in the folder /sbin/ btw. And most of those commands need 'sudo' in front of them. I also recreated my NFS file server with an SSD boot disk, but not sure if that was necessary. A few minutes after I ran the script, the JupyterHub started working.

**Comment by mrubashkin-svds** [comment] 2017-03-25 03:11
Hey @torbjornvik and @sveesible Thanks for the offer of help. Still is not working (see attached image)

I've followed @torbjornvik suggestions using ZFS on SSD boot disk, then mounted the /jupyterhub disk and could see it with df-h

That said, I don't know why the kubernetes jupyterhub pods can't connect to the file server

![image](https://cloud.githubusercontent.com/assets/17418749/24319039/0fb11f58-10ce-11e7-9117-d1f808f30edf.png)

**Comment by ghost** [comment] 2017-03-27 16:54
@mrubashkin-svds I'm not sure if this is the culprit for your problems, but the second to last command in your script (the echo) didn't work for me as it didn't have write access to /etc/exports, so I simply replaced that line with...

```
echo "$MNTPT *(rw,no_root_squash,subtree_check)" >> /tmp/exports
sudo mv /tmp/exports /etc/exports
```

 Otherwise, the only thing I can think of is to make sure you used the internal IP of the file server and maybe simply do a 'teardown' followed by another deploy of your JupyterHub.

**Comment by mrubashkin-svds** [comment] 2017-03-27 22:35
Thanks @torbjornvik trying one more time with this script on the juytyerhub-filer
```
sudo su
export DVC="/dev/disk/by-id/$(ls /dev/disk/by-id | grep "google-$(hostname)")"
export MNTPT="/"$(ls /dev/disk/by-id | grep "google-$(hostname)" | awk -F"-" '{print $NF}')
cd /sbin/
mkfs.ext4 $DVC
mkdir -p $MNTPT
mount -t ext4 $DVC $MNTPT
echo "$MNTPT *(rw,no_root_squash,subtree_check)" >> /etc/exports
sudo mv /tmp/exports /etc/exports
# manually confirmed that the exports file looked like this:   '/jupyterhub *(rw,no_root_squash,subtree_check)
/etc/init.d/nfs-kernel-server restart
```

And confirmed that the /jupyterhub was mounted:
```
root@jupyterhub-filer-vm:/sbin# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       9.8G  2.3G  7.0G  25% /
udev             10M     0   10M   0% /dev
tmpfs           743M  8.4M  735M   2% /run
tmpfs           1.9G     0  1.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           1.9G     0  1.9G   0% /sys/fs/cgroup
tmpfs           372M     0  372M   0% /run/user/1001
/dev/sdb        197G   60M  187G   1% /jupyterhub
```
Now trying to deploy the JupyterHub...

[UPDATE]
Hey, everything finally worked, thanks @torbjornvik 👍 
@sveesible would you accept a PR from myself to fix this bug in attaching the /jupyterhub filesystem?

**Comment by sveesible** [comment] 2017-03-28 17:20
good to hear.  you should note that the `df -h` command is just going to confirm that your drive is mounted.  you would then use `sudo showmount -e <your-server-ip>` to see if the NFS mount point is actually being shared.   As for the PR I can take a look as long as you've read and followed the contributions instructions.  Thanks.  They are still working on getting the File server in Launcher to work properly, meanwhile I am working on a NFS server pod with a persistent disk to make it all work in GKE.

**Comment by sveesible** [comment] 2017-04-28 16:05
There is an additional bug in the launcher for the shared filer server that does not accept any other value for the Storage Name field other than the default, which is "data".  If you leave the default there, and change the shell script to use --filer-path /data  it will work

**Closed as completed by sveesible** 2017-04-28 16:05 UTC
